#!/usr/bin/env ash
#dir="./"
url="http://192.168.1.209:8080"
#curl -X POST "$url/enabletorch"
#f=$(date +"%y%m%d_%H%M")
curl -s "$url/photo.jpg" -o A.jpg
sleep 2
curl -s "$url/photo.jpg" -o B.jpg
#curl -X POST "$url/disabletorch"
if [ -x ./build/count_ants ]; then
	./build/count_ants A.jpg B.jpg
else
	count_ants A.jpg B.jpg
fi